# Generated by Django 3.1.4 on 2021-04-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210417_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ans_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
